<a href="https://colab.research.google.com/github/Techspacenation1995/Machine_Learning/blob/main/3_0_Complete_Numpy_Tutorial_in_Python_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Definition

**Numpy** is a Python Library that provides powerful and versatile array computations, mathematical functions, and other various scientific domains. It is widely used in data science, machine learning, and scientific computing.

**Numpy** offers comprehensive mathematical calculations, random number generators, linear algebra routines, fourier transforms, and more.

Advantages of Numpy Arrays:

1.   Allows several mathematical operations
2.   Faster Operation



List vs Numpy - Time Taken

In [ ]:
from time import process_time

Time Taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0009136549999979593


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0017809359999994001


#Creating Numpy Arrays

In [ ]:
import numpy as np

In [ ]:
# List
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# Ceating a 1 dimensional Array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
# np.arrays

import numpy as np

#create numpy 1 Dimensional Array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
# To check the shape of the array
a.shape

(4,)

In [ ]:
#1D array of length all values 0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
b = np.array([(1,2,3,4), (5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4), (5,6,7,8)], dtype=float)
print(c)
#

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [ ]:
# create a numpy arrays of zeros

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy arrays of ones

y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particlular value

z = np.full((5,4), 5)  # This makes all the values to be five
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# Create an identity matrix

a = np.eye(5) # Do not highlight the number of rows or columns
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values

b = np.random.random((3,4)) # Note that all the values would be between zero and one
print(b)

[[0.71714919 0.14342163 0.35125646 0.53995526]
 [0.64755454 0.66783111 0.66834796 0.38851062]
 [0.22632671 0.36966542 0.4811943  0.63857784]]


In [ ]:
# Create random integer values array within a specific range
c = np.random.randint(10,100,(3,5)) # Note that all the values would be between 10 to 100
print(c)

[[95 16 44 76 27]
 [70 43 50 53 33]
 [12 78 85 17 70]]


In [ ]:
# array of evenly spaced values --> specifying the number of values that you want
d = np.linspace(10, 30, 6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10, 30, 5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2) # The asarray function convert any datatype to a numpy array
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[46 38 84 36 23]
 [47 65 58 89 15]
 [71 65 33 18 70]
 [20 45 12 28 78]
 [46 68 16 66 65]]


In [ ]:
# array dimension

print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
#number of element in an array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical Operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # Concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[1 1 6]
 [9 7 2]
 [8 0 1]]
[[18 18 17]
 [11 16 17]
 [19 15 15]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[19 19 23]
 [20 23 19]
 [27 15 16]]
[[-17 -17 -11]
 [ -2  -9 -15]
 [-11 -15 -14]]
[[ 18  18 102]
 [ 99 112  34]
 [152   0  15]]
[[0.05555556 0.05555556 0.35294118]
 [0.81818182 0.4375     0.11764706]
 [0.42105263 0.         0.06666667]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[0 7 2]
 [1 8 6]
 [0 8 3]]
[[13 13 16]
 [10 10 10]
 [17 14 19]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[13 20 18]
 [11 18 16]
 [17 22 22]]
[[-13  -6 -14]
 [ -9  -2  -4]
 [-17  -6 -16]]
[[  0  91  32]
 [ 10  80  60]
 [  0 112  57]]
[[0.         0.53846154 0.125     ]
 [0.1        0.8        0.6       ]
 [0.         0.57142857 0.15789474]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 7 7]
 [4 7 5]]
(2, 3)


In [ ]:
# transpose of matrix
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[0 4]
 [7 7]
 [7 5]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 9 4]
 [8 8 4]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[5 8]
 [9 8]
 [4 4]]
(3, 2)


In [ ]:
# reshaping array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 5 6]
 [4 5 8]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[8 5]
 [6 4]
 [5 8]]
(3, 2)
