<a href="https://colab.research.google.com/github/Techspacenation1995/Machine_Learning/blob/main/3_1_Complete_Numpy_Tutorial_in_Python_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#dtype

The desired data-type for the array. If not given, then the type will be determined as the minimum type required to hold the object in the sequence.

In [ ]:
import numpy as np

In [ ]:
np.array([11, 23, 44], dtype='f') # We can alternatively use dtype = float

array([11., 23., 44.], dtype=float32)

In [ ]:
np.array([11, 23, 44], dtype='i')

array([11, 23, 44], dtype=int32)

In [ ]:
np.array([11, 23, 44], dtype='U')

array(['11', '23', '44'], dtype='<U2')

In [ ]:
np.array([11, 23, 44], dtype='S')

array([b'11', b'23', b'44'], dtype='|S2')

In [ ]:
np.array([11, 23, 44], dtype='O')

array([11, 23, 44], dtype=object)

In [ ]:
np.array([11, 23, 44], dtype= bool)

array([ True,  True,  True])

In [ ]:
np.array([11, 23, 44], dtype= complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

#Arange

**np.arange()** is a function in NumPy used to create arrays with evenly spaced values within a specified range. It's similar to Python's built-in **range()** but returns a NumPy array instead of a list, and supports float steps.

**Syntax**

numpy.arange([start,] stop[, step], dtype=None)


**Parameters**


start (optional): Start of interval (inclusive). Defaults to 0.

stop: End of interval (exclusive).

step (optional): Spacing between values. Defaults to 1.

dtype (optional): The type of the output array.

In [ ]:
#  Basic usage

import numpy as np

arr = np.arange(5)
print(arr)  # Output: [0 1 2 3 4]

[0 1 2 3 4]


In [ ]:
# With start and stop

arr = np.arange(2, 10)
print(arr)  # Output: [2 3 4 5 6 7 8 9]

[2 3 4 5 6 7 8 9]


In [ ]:
# With step

arr = np.arange(1, 10, 2)
print(arr)  # Output: [1 3 5 7 9]

[1 3 5 7 9]


In [ ]:
# With float step

arr = np.arange(0, 1, 0.2)
print(arr)

[0.  0.2 0.4 0.6 0.8]


In [ ]:
# Specifying dtype

arr = np.arange(1, 5, dtype='f')
print(arr)

[1. 2. 3. 4.]


#Reshape

np.reshape() in NumPy is used to change the shape of an array without changing its data. It returns a new view (or sometimes a copy) of the original array with the specified shape.

**Syntax**

numpy.reshape(a, newshape)


a: The array to reshape.

newshape: Tuple defining the new shape. One dimension can be -1, which means "infer this dimension automatically".

In [ ]:
# Reshape 1D array to 2D

import numpy as np

arr = np.arange(6)
print(arr)
reshaped = np.reshape(arr, (2, 3))
print(reshaped)
# Output:
# [[0 1 2]
#  [3 4 5]]

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [ ]:
# Using -1 to infer dimension

arr = np.arange(6)
print(arr)
reshaped = np.reshape(arr, (2, -1))
print(reshaped)
# Output:
# [[0 1 2]
#  [3 4 5]]


[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In NumPy, when you pass -1 as one of the dimensions in .reshape(), you're telling NumPy:

“Hey, you figure out this dimension for me, based on the size of the array and the other dimensions I’ve given.”

NumPy will automatically calculate the value that makes the reshape possible, without changing the total number of elements.

In [ ]:
# Reshape 2D to 1D

arr = np.array([[1, 2], [3, 4]])
print(arr)
flat = arr.reshape(-1)
print(flat)
# Output: [1 2 3 4]

[[1 2]
 [3 4]]
[1 2 3 4]


This is a 2D array with shape (2, 2) — meaning 2 rows and 2 columns.

Total elements = 2 × 2 = 4

You're telling NumPy:

“Flatten this array into a 1D array, and you figure out how many elements go in it.”

Since the total number of elements is 4, NumPy reshapes it to: [1, 2, 3, 4]

In [ ]:
# 3D Reshape

arr = np.arange(12)
print(arr)
reshaped = arr.reshape((2, 3, 2))
print(reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


#np.zeros() — All Zeros

**USES**

Create an array filled with zeros.

 **Syntax:**

 np.zeros(shape, dtype=float)

In [ ]:
import numpy as np

zero_arrays = np.zeros((2,3))
print(zero_arrays)

[[0. 0. 0.]
 [0. 0. 0.]]


#np.ones() - All ones

**USES**

Create an array filled with ones.

**Syntax:**

np.ones(shape, dtype=float)

In [ ]:
ones_array = np.ones((2, 3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


**Common Parameters:**

**shape:** Tuple specifying the shape (e.g., (3, 4) for 3x4)

**dtype:** Optional, like int, float, etc.

#What is np.linspace()

np.linspace() generates a specified number of evenly spaced values between a start and stop value.

**Syntax:**

numpy.linspace(start, stop, num=50, endpoint=True, dtype=None)

**Parameters:**

start: The starting value of the sequence.

stop: The ending value of the sequence.

num: (Optional) Number of samples to generate. Default is 50.

endpoint: (Optional) If True (default), include the stop value. If False, exclude it.

dtype: (Optional) Data type of the output array.

In [ ]:
# Basic Use

import numpy as np

arr = np.linspace(0, 10, 5)
print(arr)


[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# Excluding endpoint

arr = np.linspace(0, 10, 5, endpoint=False)
print(arr)

[0. 2. 4. 6. 8.]


In [ ]:
#  Used with integer(Forced dtype)

arr = np.linspace(0, 10, 5, dtype=int)
print(arr)

[ 0  2  5  7 10]


When to use linspace() vs arange()

Use Case	Use

You know the step size	       ------             np.arange()

You know the number of points	  -----            np.linspace()

You need precise spacing with floats -------	Prefer linspace() (more reliable)

#Identity Matrix

An identity matrix is a square matrix (same number of rows and columns) with:

* All 1s on the diagonal (from top-left to bottom-right)

* All other elements are 0


**Syntax in NumPy:**

np.identity(n, dtype=float)

* n: The number of rows and columns (since it's square)
* dtype: (optional) Data type (like int or float)



In [ ]:
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
I = np.identity(3, dtype=int)
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Why is it important?

* Used in linear algebra and matrix operations

* Acts like the “do nothing” matrix during multiplication

* Helps in solving equations, finding inverses, and understanding transformations

Let's compare np.identity() vs np.eye() — they both create matrices with 1s on a diagonal, but they serve slightly different purposes.


**np.identity(n)**

Creates a square identity matrix.

Only one parameter: the size (n x n).

Diagonal of 1s from top-left to bottom-right.

Always starts on the main diagonal (no shifting).


**np.eye(N, M=None, k=0)**

More flexible than identity().

Can create non-square matrices.

You can shift the diagonal using k:

k=0: main diagonal

k=1: one above the main

k=-1: one below the main

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# For non square matrix

print(np.eye(3, 4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
# For shifted diagonal matrix (k = 1)

print(np.eye(3, 4, k=1))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# For shifted diagonal matrix (k = -1)

print(np.eye(3, 4, k=-1))

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


**Summary**

|Features| np.identity()| np.eye()|
|---|---|---|
|Shape| Always square in nature (nxn)| Can be rectangular (N x M)|
|Diagonal Shift| No | Yes, with k *prameter*|
|Simplicity| simpler for identity| Mor flexible for variations|

#ARRAY ATTRIBUTES

Let's do a deep dive into the different attributes of NumPy arrays. These attributes help you understand and work with the structure and properties of arrays effectively.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

#1. arr.ndim --> Number of dimensions

In [ ]:
arr.ndim # This means its a two dimensional array

2

#2. arr.shape --> Shape of the array



In [ ]:
arr.shape # Displays the number of rows and columns

(2, 3)

#3. arr.size --> Total number of elements

Helps us determine the total number of element in the array

In [ ]:
arr.size # It can also be gotten by multiplying the number of rows and arrows

6

#4. arr.dtype - Data type of each elements

In [ ]:
arr.dtype

dtype('int64')

#5. arr.itemsize → Size in bytes of one array element

In [ ]:
arr.itemsize # Output: 8  # for int64 (8 bytes)

8

#6. arr.nbytes → Total memory used

In [ ]:
arr.nbytes # Meaning: 6 elements × 8 bytes = 48 bytes used in memory.

48

#7. arr.T → Transpose of the array

In [ ]:
arr.T # Swaps rows with columns — useful in matrix math.

array([[1, 4],
       [2, 5],
       [3, 6]])

#8. arr.flat → Iterator over flattened array

In [ ]:
for item in arr.flat:
    print(item, end=' ')  #Gives access to every element in a flat (1D) way.

1 2 3 4 5 6 

#9. arr.data → Memory buffer (advanced use)

In [ ]:
arr.data

#Overall Summary

|Attribute| Description|
|---|---|
|ndim| Number of dimensions (axes)|
|shape| Tuple showing array size per axis|
|size| Total number of elements|
|dtype| data type of the element|
|itemsize| Size (in bytes) of each element|
|nbytes| Total memory size (in bytes)|
|T|Transpose of the array|
|flat|Flat iterator over all elements|
|data| Memory buffer info|