<a href="https://colab.research.google.com/github/Techspacenation1995/Machine_Learning/blob/main/3_2_Complete_Numpy_Tutorial_in_Python_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Array Operations

The core power of NumPy is its ability to perform fast, efficient operations on arrays without writing loops.



#Scalar Operation

 scalar operation means performing a mathematical operation between a NumPy array and a single number (scalar).

Instead of writing a loop to apply a value to each element, NumPy does it automatically — element-wise — using broadcasting.

In [ ]:
# 1. Addition

import numpy as np

arr = np.array([1, 2, 3])

result = arr + 5

result

array([6, 7, 8])

Every element in arr has 5 added to it.

In [ ]:
#  2. Subtraction

result = arr - 1

result

array([0, 1, 2])

In [ ]:
# 3. Multiplication

result = arr * 2

result

array([2, 4, 6])

In [ ]:
# 4. Division

result = arr / 2

result

array([0.5, 1. , 1.5])

In [ ]:
# 5. Exponentiation

result = arr ** 2

result

array([1, 4, 9])

In [ ]:
# 6. Modulus (remainder)

result = arr % 2

result
#

array([1, 0, 1])

#Relational Operations in NumPy

These operations compare each element in a NumPy array to a scalar or another array and return **boolean arrays** (True or False), which are super useful for filtering, masking, and logic-building in data processing.



In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr > 3)

[False False False  True  True]


Comparison with Another Array

In [ ]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

print(a > b)

[False False  True]


**Why Is This Useful?**

You can use the result to filter or select data.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

mask = arr > 3

filtered_data = arr[mask]

filtered_data

array([4, 5])

Combining Conditions (Logical Operations)

You can combine relational operators with:

* & (AND)

* | (OR)

* ~ (NOT)

In [16]:
arr = np.array([1, 2, 3, 4, 5])

print((arr > 2) & (arr > 5))

[False False False False False]


Check All or Any

In [18]:
print(np.all(arr > 2))

False


In [20]:
print(np.any(arr > 2))

True


#Vector Operation

NumPy provides powerful tools for element-wise operations, which makes working with vectors very efficient. These operations allow you to perform various mathematical tasks without needing explicit loops.

#🔹 Vector Operations Overview

* Element-wise operations: Operations are performed on each element of the vector.

* Linear algebra operations: Operations like dot product, cross product, etc., apply to vectors.

* Aggregation operations: Operations to summarize or reduce vector data, like sum, mean, etc.

#✅ 1. Element-wise Operations

These are the same as scalar operations, but here, both operands are vectors (1D arrays).

➕ Addition:

In [21]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

c = a + b
c

array([5, 7, 9])

➖ Subtraction:

In [23]:
c = a - b
c

array([-3, -3, -3])

✖️ Multiplication:

In [24]:
c = a * b
c

array([ 4, 10, 18])

➗ Division:

In [25]:
c = a / b
c

array([0.25, 0.4 , 0.5 ])

Exponentiation:

In [26]:
c = a ** b
c

array([  1,  32, 729])

#✅ 2. Vector Dot Product

The dot product is a crucial operation in linear algebra. It's the sum of the products of corresponding elements in two vectors.

In [28]:
dot_product = np.dot(a,b)
print(dot_product)

32


You can also use @ to compute the dot product (recommended):

In [29]:
dot_product = a @ b
print(dot_product)

32


✅ 3. Cross Product (in 3D space)


The cross product is only defined for 3-dimensional vectors. It returns a vector that is perpendicular to both input vectors.

In [30]:
cross_product = np.cross(a,b)
print(cross_product)
#

[-3  6 -3]


The result vector is perpendicular to both a and b.