<a href="https://colab.research.google.com/github/Techspacenation1995/Machine_Learning/blob/main/3_2_Complete_Numpy_Tutorial_in_Python_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Array Operations

The core power of NumPy is its ability to perform fast, efficient operations on arrays without writing loops.



#Scalar Operation

 scalar operation means performing a mathematical operation between a NumPy array and a single number (scalar).

Instead of writing a loop to apply a value to each element, NumPy does it automatically — element-wise — using broadcasting.

In [ ]:
# 1. Addition

import numpy as np

arr = np.array([1, 2, 3])

result = arr + 5

result

array([6, 7, 8])

Every element in arr has 5 added to it.

In [ ]:
#  2. Subtraction

result = arr - 1

result

array([0, 1, 2])

In [ ]:
# 3. Multiplication

result = arr * 2

result

array([2, 4, 6])

In [ ]:
# 4. Division

result = arr / 2

result

array([0.5, 1. , 1.5])

In [ ]:
# 5. Exponentiation

result = arr ** 2

result

array([1, 4, 9])

In [ ]:
# 6. Modulus (remainder)

result = arr % 2

result
#

array([1, 0, 1])

#Relational Operations in NumPy

These operations compare each element in a NumPy array to a scalar or another array and return **boolean arrays** (True or False), which are super useful for filtering, masking, and logic-building in data processing.



In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr > 3)

[False False False  True  True]


Comparison with Another Array

In [ ]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

print(a > b)

[False False  True]


**Why Is This Useful?**

You can use the result to filter or select data.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

mask = arr > 3

filtered_data = arr[mask]

filtered_data

array([4, 5])